console.log(`Firmware Scraper v4.0 (single-site, accumulating)`);
console.log(`\nSource: https://ximitime.com/hyperos/ (Xiaomi HyperOS device database)`);
console.log(`\nUsage:`);
console.log(`  node fetch_roms.js                      # scrape hyperos`);
console.log(`  node fetch_roms.js --batch 50            # max NEW items fetched this run (default 50)`);
console.log(`  node fetch_roms.js --out-dir ./feed     # specify output/state directory`);
console.log(`\nBehavior:`);
console.log(`  - Every run crawls the ENTIRE site (all devices, all pages, no limit)`);
console.log(`    to discover what versions exist.`);
console.log(`  - Already-fetched versions (tracked in roms_hyperos.json) are never`);
console.log(`    re-fetched or re-downloaded.`);
console.log(`  - Of the newly discovered versions, only --batch (default 50) are`);
console.log(`    actually fetched per run; the rest are picked up on the next run.`);
console.log(`  - Results accumulate across runs — nothing is overwritten, and there`);
console.log(`    are never duplicate entries in the JSON/RSS output.`);
console.log(`\nOutput (accumulated, in --out-dir):`);
console.log(`  roms_hyperos.json   - structured metadata`);
console.log(`  rss_hyperos.xml     - RSS feed with direct download links`);
console.log(`  roms_all.json       - combined metadata (mirrors roms_hyperos.json)`);
console.log(`  rss_all.xml         - combined RSS feed (mirrors rss_hyperos.xml)`);
